In [3]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [4]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`

null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`

np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
np.arange(0, 9)
grid = np.arange(0, 9).reshape(3,3)
grid

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [15]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`

np.random.random((3,3))


array([[0.39884332, 0.22262833, 0.43530106],
       [0.93918835, 0.31201774, 0.0413177 ],
       [0.88439208, 0.08738648, 0.77157693]])

In [25]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`

grid = np.random.random((10,10))
print(grid.min())
print(grid.max())

0.009975122739402709
0.982146152991574


In [27]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
a = np.arange(0, 31)
np.mean(a)


15.0

In [37]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
values = [1, 2, 3, 4]

# Create a matrix with the values below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [43]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`

grid = np.random.random((5,5))

mean = np.mean(grid)
std = np.std(grid)

# Normalize the matrix
normalized_grid = (grid - mean) / std


In [46]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
a = np.arange(10, 50)
b = np.arange(20, 100)

# Find common values
common_values = np.intersect1d(a, b)
common_values

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
a = np.arange(0, 11).sort()
a

In [57]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
a = np.random.random(10)

a_max = np.argmax(a)

# Replace the maximum value with 0
a[a_max] = 0
a

array([0.83824343, 0.78564873, 0.57095943, 0.37371091, 0.36304352,
       0.33169781, 0.07295902, 0.        , 0.11800403, 0.75724287])

In [68]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`
a = np.random.random((4, 4))

row_means = a.mean(axis=1, keepdims=True)

normalized_a = a - row_means
normalized_a

array([[-0.08536985, -0.01189738,  0.11479341, -0.01752619],
       [ 0.05922722,  0.3038982 , -0.24051386, -0.12261156],
       [-0.18914985,  0.30606893, -0.25581472,  0.13889564],
       [ 0.19534513, -0.19374135,  0.02289399, -0.02449777]])

In [ ]:
#### 17. How to get the n largest values of an array (★★★)
#`Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`

In [4]:
Z = np.arange(10000)
np.random.shuffle(Z)

n = 5

largest_indices = np.argpartition(Z, -n)[-n:]

largest_values = Z[largest_indices]

largest_values_sorted = np.sort(largest_values)[::-1]

In [8]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`

matrix = np.random.randint(1, 7, size=(5, 3)) 

result = np.where(matrix > 4, matrix**2, matrix)
matrix

array([[6, 6, 2],
       [6, 5, 5],
       [2, 2, 6],
       [1, 6, 5],
       [2, 1, 2]])